config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users
  resources :users

  resources :vms

  #resources :tasks

  #root to: "users#index"
  root to: "pages#home"

  post "upload" => 'tasks#upload'

  resources :tasks do
  	collection do
  		get 'pending'
      get 'current'
  	end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	
	belongs_to :user

	serialize :email, Array
	
	has_and_belongs_to_many :vms

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks

end

app/models/vm.rb
class Vm < ActiveRecord::Base

	has_and_belongs_to_many :tasks
	
end

app/controllers/application_controller.rb
require File.expand_path("../../config.rb", __FILE__)
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end


  def authenticate
    if current_user
      true
    else
      redirect_to new_user_session_path
    end
  end

  def private
    if current_user
      true
    else
      redirect_to new_user_session_path
    end
  end

  def admin
  	if current_user
  		if current_user.role == "admin"
  			true
  		else
  			redirect_to root_path
  		end
    else
      redirect_to new_user_session_path
  	end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
require 'colorize'
class TasksController < ApplicationController

	before_action :find_task, only: [:edit, :show, :update, :destroy]
	before_filter :authenticate, :except => [:new, :create, :pending, :current]

	def index
	  #@tasks = Task.all
	  @tasks = Task.where(user_id: current_user.id)
	end

	def new
	  @task = Task.new
	  @time = DateTime.now.strftime('%Q')
	  vmss = getVms()
	  @machines = Array.new(vmss.size, obj=nil)
	  @Computers = Struct.new( :name, :state)
	  for i in 0..vmss.size-1
	    @machines[i] = @Computers.new("#{convertVmName(vmss[i])}","#{vmss[i]}")
	  end
	  @os = ["Windows 2000", "Windows XP", "Windows server 2003", "Windows Vista", "Windows Server 2008", "Windows 7", "Windows Server 2008 R2", "Windows 8", "Windows Server 2012", "Windows 8.1", "windows Server 2012 R2", "Windows 10"]
	  @keyword = ["win 2000", "xp", "2003", "vista", "2008 x", "7", "2008 R2", "8.0", "2012 A", "8.1", "2012 R2", "10"]
	  @vms = Vm.all
	end

	def create
	  @task = Task.new(task_params)
	  if @task.save
	    current_user.tasks << @task
	    redirect_to @task
	  else
	   render 'new'
	  end
	end

	def show
	  #action find_task
	end

	def edit
	  #action find_task    
	end

	def update
	  #action find_task 
	  @params = params[:task]
	  @task.update_attributes(task_params(@params))
	  if @task.errors.empty?
	    redirect_to task_path(@task)
	  else
	    render "edit"
	  end
	end
	  
	def destroy
	  #action find_task  
	  @task.destroy
	  redirect_to tasks_path
	end

	def task_params(parameter)
	  parameter.permit(:name, :cmd, :file, :status, :progress, {:email => []}, :timeout, :restore, :number, :priority)
	end

	def find_task
	  @task = Task.find(params[:id])
	  if @task.user_id == current_user.id
	  	true
	  else
	  	redirect_to tasks_path
	  end
	end

	def upload
		@parameters = params
		@params = params[:task]
		@file = @params[:file]
		if @params[:file]
			@params[:file] = @params[:file][0].original_filename
		else
			@params[:file] = nil
		end
		@params[:email] << "#{current_user.email}"
		@params[:status] = "Wait"
		@params[:progress] = 0
		@params[:timeout] =  @params[:timeout].to_i
		@params[:number] = @params[:number].to_i
		@params[:priority] = 0
		@command_line = @params[:cmd] 
		@task = Task.new(task_params(@params))
		if @task.save
			@task.priority = @task.id
			FileUtils.mkdir_p "#{$pathPub}/Files/#{@task.id}"
			if @file
				for i in 0..@file.size-1
					tmp = @file[i].tempfile
					@original_file_name = "#{@file[i].original_filename}"
					file = File.join("#{$pathPub}/Files/#{@task.id}", @file[i].original_filename)
					@file_size = File.size(tmp)
					File.open(file,"wb") do |f|
          				f.write(tmp.read)
          			end
				end
			end
			File.open("#{$pathPub}/Files/#{@task.id}/test.bat", 'w') do |f| 
		        f.write("@echo off\n")
		        f.write("timeout /t 10\n")
		        f.write("pushd %~dp0\n")
		        if @file
		          f.write("%~dp0\\#{@original_file_name} #{@command_line} > %~dp0\\stdout.txt 2> %~dp0\\stderror.txt\n")
		        else
		          f.write("#{@command_line} > %~dp0\\stdout.txt 2> %~dp0\\stderror.txt\n")
		        end
		        f.write("echo %errorlevel% > %~dp0\\retcode.txt\n")
		        f.write("shutdown /s /t 30\n")
		    end
		else
			render 'new'
		end
		if @task.save
		  	current_user.tasks << @task
		  		@vms = Vm.where(:id => @params[:vms])
		  		@task.vms << @vms
		   	redirect_to @task
		else
		   	render 'new'
		end
	end

	def pending
	  @task = Task.new
	  @tasks = Task.where(status: "Wait").order("priority")
	end

	def current
	  @task = Task.new
	  @tasks = Task.where(status: "Working")
	end

  private

	def getVms()
	  @vmslistraw = `#{$pathVBox} list vms`
	  @vmlist = @vmslistraw.split(/\n/)
	  return @vmlist
	end

	def convertVmName(vmName)
	  newName = vmName.delete("\"").split(" {")
	  return newName[0]
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:new, :create]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :role)
    end
end

app/controllers/vms_controller.rb
class VmsController < ApplicationController

	before_action :find_vm, only: [:show, :edit, :update, :destroy]
	before_filter :admin

	def getVms()
	  @vmslistraw = `#{$pathVBox} list vms`
	  @vmlist = @vmslistraw.split(/\n/)
	  return @vmlist
	end

	def convertVmName(vmName)
	  newName = vmName.delete("\"").split(" {")
	  return newName[0]
	end

	def convertVmHash(vmName)
	  newName = vmName.scan(/(\{[\w-]+\})/)
	  return newName[0][0]
	end

	def index
		@vms = Vm.all
	end

	def new
	  @vm = Vm.new
	end

	def create
	  @params = params[:vm]
	  vmss = getVms()
	  @os = ["Windows 2000", "Windows XP", "Windows server 2003", "Windows Vista", "Windows Server 2008", "Windows 7", "Windows Server 2008 R2", "Windows 8", "Windows Server 2012", "Windows 8.1", "Windows Server 2012 R2", "Windows 10"]
	  @keyword = ["win 2000", "xp", "2003", "vista", "2008 x", "7", "2008 R2", "8.0", "2012 A", "8.1", "2012 R2", "10"]
	  @vms = Vm.all
	  for i in 0..@vms.size-1
	  	if vmss.size != 0
			if vmss.to_s.include? "#{@vms[i].vhash}"
			else
				@vms[i].destroy
			end
		else
			puts "No vms"
		end
	  end


	  for i in 0..vmss.size-1
	  	for j in 0..@os.size-1
			if convertVmName(vmss[i]).include? "#{@keyword[j]}"
				@params[:name] = "#{convertVmName(vmss[i])}".to_s
	  			@params[:vhash] = "#{convertVmHash(vmss[i])}"
	  			@params[:subname] = "#{@os[j]}"
	  			@params[:timeout] = 0
	  			@vm = Vm.new(vm_params(@params))
	  			begin
				  if @vm.save
				    @z = "Yes"
				  else
				   	@z = "No"
				  end
				rescue
				end
			end
		end
	  end
	  redirect_to vms_path
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	  @vm.destroy
	  redirect_to vms_path
	end

	def vm_params(parameter)
	  parameter.permit(:name, :vhash, :subname, :name, :timeout)
	end

	private

    def find_vm
      @vm = Vm.find(params[:id])
    end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vms_helper.rb
module VmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Robogroft" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="col-sm-2">
          <%= link_to "Robogroft", pages_home_path, :class => 'navbar-brand' %>
        </div>
        <div class="col-md-8"></div>

        <div class="pull-right">
          <div class="btn-group">
              <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu pull-right">
                <% if current_user %>
                  <li><%= link_to current_user.name, user_path(current_user.id) %></li>
                  <li><%= link_to t('user.edit'), edit_user_path(current_user), :class => 'navbar-link' %></li>
                  <% if current_user.role == "admin" %>
                      <li><%= link_to t('user.users'), "/users"%></li>
                      <li><%= link_to t('tasks.vms'), "/vms"%></li>
                  <% end %>
                  <li role="separator" class="divider"><hr></li>
                  <li><%= link_to t('session.log_out'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                  <li><%= link_to_unless_current "English", locale: "en" %></li>
                  <li><%= link_to_unless_current "Русский", locale: "ru" %></li>
                <% else %>
                  <li><%= link_to t('session.signup'), new_user_registration_path, :class => 'navbar-link'  %></li>
                  <li><%= link_to t('session.log_in'), new_user_session_path, :class => 'navbar-link'  %></li>
                  <li><%= link_to_unless_current "English", locale: "en" %></li>
                  <li><%= link_to_unless_current "Русский", locale: "ru" %></li>
                <% end %>
              </ul>
            </div>
        </div>

      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
        <div class="thumbnail">
          <%= image_tag("/robogroft2.jpg") %>
          <% if current_user %>
            <div >
              <h3><%= $mes %></h3>
            </div>
          <% else %>
            <div >
              <%= t('session.introduce') %>:
              <%= link_to t('session.log_in'), new_user_session_path, :class => 'navbar-link'  %> <%= t('all.or') %> <%= link_to t('session.signup'), new_user_registration_path, :class => 'navbar-link'  %>
            </div>
          <% end %>
        </div>
      </div>
        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-sm-2">
          <div class="list-group">
            <%= link_to t('all.home'), pages_home_path, :class => 'list-group-item active', :role => "button"%>
            <% if current_user %>
              <%= link_to t('tasks.create'), new_task_path, :class => 'list-group-item', :role => "button"%>
            <% else %>
              <%= link_to t('tasks.create'), new_task_path, :onclick => "return false", :class => 'list-group-item disabled', :disabled => "disabled", :role => "button"%>
            <% end %>
            <%= link_to t('tasks.mytask'), tasks_path, :class => 'list-group-item', :role => "button"%>
            <%= link_to t('tasks.current'), current_tasks_path, :class => 'list-group-item', :role => "button"%>
            <%= link_to t('tasks.pending'), pending_tasks_path, :class => 'list-group-item', :role => "button"%>
            <a href="#" class="list-group-item" role="button"><p><%= t('tasks.results') %></p></a>
          </div>
      </div>
      </div><!--/row-->

      <footer class="container-fluid text-center">
        <p>&copy; Robogroft 2015</p>
      </footer>
      
    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<% if current_user %>
			<h4><%= current_user.name %></h4>
		<% else %>
			<h4><%= t('all.user') %></h4>
		<% end %>
	</div>
	<div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
		<%= t('pages.tasks') %>: 
	</div>
</div>

app/views/tasks/current.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t('tasks.current') %></h4>
	</div>
	<div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
		<% for i in 0..@tasks.size-1 %>
			<b><%= t('tasks.name') %>:</b> <%= @tasks[i].name %><br>
			<b><%= t('tasks.creator') %>:</b> <% u = User.where(id: @tasks[i].user_id).first %><%= u.name %><br>
		<% end %>
	</div>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/tasks/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('tasks.edit') %></h4>
  </div>
  <div class="panel-body">
    <%= form_for @task do |e| %>
      <%= t('tasks.name') %>:
        <div class="input-group" name='dynamic'>    
          <%= e.text_field :name, :class => "form-control"%>
          <span class="input-group-addon"><%= t('tasks.name') %></span>
        </div><br/>
      <%= t('tasks.cmd') %>:
        <div class="input-group">
          <%= e.text_field :cmd, :class => "form-control", :size => 58 %><br/>
          <span class="input-group-addon"><%= t('tasks.cmd') %></span>
        </div><br/>
      <%= t('tasks.timeout') %>:
        <div class="input-group">
          <%= e.text_field :timeout, :class => "form-control" %>
          <span class="input-group-addon"><%= t('all.seconds') %></span>
        </div><br/>
      <%= t('tasks.num_machines') %>:
        <%= e.select :number, (['1', '2', '3', '4'].map {|i| [i,i] }), {}, {:class => "form-control"} %><br/>
      <%= e.submit t('all.save'), :class => "btn btn-default btn-md btn-block" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t('tasks.my') %></h4>
	</div>
	<div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
		<table class="table table-hover">
			<tr align="center">
				<td width="20px"><%= t('tasks.name') %> </td>
				<td width="20px"><%= t('tasks.email') %> </td>
				<td><%= t('tasks.status') %> </td>
				<td><%= t('tasks.timeout') %> </td>
				<td><%= t('tasks.progress') %> </td>
				<td><%= t('tasks.cmd') %> </td>
				<td><%= t('tasks.file') %> </td>
				<td><%= t('tasks.vms') %> </td>
				<td><%= t('tasks.rest') %>? </td>
				<td><%= t('tasks.number') %> </td>
			</tr>
			<% @tasks.each do |e| %>
				<tr align="center">
					<td><%= link_to e.name, task_path(e)%></td>
					<td>
						<% for i in 0..e.email.size-1 %>
							<%= e.email[i] %></br>
						<% end %>
					</td>
					<td><%= e.status %></td>
					<td><%= e.timeout %></td>
					<td><%= e.progress %></td>
					<td><%= e.cmd %></td>
					<td><%= e.file %></td>
					<td>
						<% for i in 0..e.vms.size-1 %>
							<%= e.vms[i].name %></br>
						<% end %>
					</td>
					<td><%= e.restore %></td>
					<td><%= e.number %></td>
				</tr>
			<% end %>
		</table>
		<%= link_to t('tasks.add'), new_task_path %>
	</div>
</div>

app/views/tasks/pending.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t('tasks.pending') %></h4>
	</div>
	<div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
		<table class="table table-hover">
			<tr align="center">
				<td><%= t('tasks.num') %>: </td>
				<td><%= t('tasks.name') %> </td>
				<td><%= t('tasks.creator') %> </td>
				<td><%= t('tasks.status') %> </td>
				<td><%= t('tasks.progress') %> </td>
			</tr>
			<% for i in 0..@tasks.size-1 %>
				<tr align="center">
					<td><p data-toggle="tooltip" data-placement="top" title="Number"><%= i+1 %></p></td>
					<td><p data-toggle="tooltip" data-placement="top" title="Task name"><%= link_to @tasks[i].name, task_path(@tasks[i])%></p></td>
					<td><p data-toggle="tooltip" data-placement="top" title="Creator"><% u = User.where(id: @tasks[i].user_id).first %><%= u.name %></p></td>
					<td><p data-toggle="tooltip" data-placement="top" title="Status"><%= @tasks[i].status %></p></td>
					<td><p data-toggle="tooltip" data-placement="top" title="Progress"><%= @tasks[i].progress %></p></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/tasks/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= @task.name %></h4>
	</div>
	<div class="panel-body">
		<table class="table table-hover">
			<tr>
				<td><b><%= t('tasks.email') %>: </b></td>
				<td>
					<% for i in 0..@task.email.size-1 %>
						<%= @task.email[i] %></br>
					<% end %>
				</td>
			</tr>
			<tr>
				<td><b><%= t('tasks.status') %>: </b></td>
				<td><%= @task.status %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.timeout') %>: </b></td>
				<td><%= @task.timeout %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.progress') %>: </b></td>
				<td><%= @task.progress %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.cmd') %>: </b></td>
				<td><%= @task.cmd %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.file') %>: </b></td>
				<td><%= @task.file %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.rest') %> </b></td>
				<td><%= @task.restore %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.number') %>: </b></td>
				<td><%= @task.number %></td>
			</tr>
			<tr>
				<td><b><%= t('tasks.vms') %>: </b></td>
				<td>
					<% for i in 0..@task.vms.size-1 %>
						<%= @task.vms[i].name %></br>
					<% end %>
				</td>
			</tr>
		</table>
	</div>
	<%= link_to t('all.edit'), edit_task_path, :class => 'btn btn-default btn-xs' %>
	<%= link_to t('all.delete'), @task, method: :delete, :class => 'btn btn-default btn-xs' %>
</div>

app/views/tasks/upload.html.erb
<b>Name :</b> <%= @parameters[:task][:name] %><br />
<b>Vms :</b> <%= @parameters[:task][:vms] %><br />
<b>File :</b> <%= @parameters[:task][:file] %><br />
<b>Cmd :</b> <%= @parameters[:task][:cmd] %><br />
<b>Timeout :</b> <%= @parameters[:task][:timeout] %><br />
<b>Number :</b> <%= @parameters[:task][:number] %><br />
<b>Restore :</b> <%= @parameters[:task][:restore] %><br />
<b>Emails :</b> <%= @parameters[:task][:email] %><br />
_________________________________________________<br />
<b>User</b><br />
<b>Id :</b> <%= @current_user.id %><br />
<b>Name :</b> <%= @current_user.name %><br />
<b>Email :</b> <%= @current_user.email %><br />
*************************************************<br />
<%= @params %><br />
*************************************************<br />
<b>File :</b> <%=  @parameters %><br />
*************************************************<br />
<% for i in 0..@parameters[:task][:email].size-1 %>
	<%= i %> : <%= @parameters[:task][:email][i] %><br />
<% end %>
*************************************************<br />
<b>Params :</b> <%=  params %><br />
*************************************************<br />

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <span class="input-group-addon"><%= f.label t('user.name') %></span>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group">
    <span class="input-group-addon"><%= f.label t('user.email') %></span>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <br>
  <% if current_user.role == "admin" %>
    <div class="input-group">
      <span class="input-group-addon"><%= f.label t('user.role') %></span>
      <%= f.text_field :role, :class => "form-control" %>
    </div>
    <br>
  <% end %>
  <div class="actions">
    <%= f.submit t('all.confirm'), :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t('user.editing') %></h4>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<%= link_to t('user.show'), @user, :class => 'btn btn-default btn-xs' %>
	<%= link_to t('all.back'), users_path, :class => 'btn btn-default btn-xs' %>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  <h4><%= t('user.listing') %></h4>
  </div>

  <div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t('user.name') %></th>
        <th><%= t('user.email') %></th>
        <th><%= t('user.role') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= link_to t('all.show'), user, :class => 'btn btn-default btn-xs' %></td>
          <td><%= link_to t('all.edit'), edit_user_path(user), :class => 'btn btn-default btn-xs' %></td>
          <td><%= link_to t('all.delete'), user, method: :delete, data: { confirm: t('all.confirm') }, :class => 'btn btn-danger btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>

  <%= link_to t('user.new'), new_user_registration_path, :class => 'btn btn-default btn-xs' %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t('user.info') %></h4>
	</div>
	<div class="panel-body">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong><%= t('user.name') %>:</strong>
		  <%= @user.name %>
		</p>

		<p>
		  <strong><%= t('user.email') %>:</strong>
		  <%= @user.email %>
		</p>

		<p>
		  <strong><%= t('user.role') %>:</strong>
		  <%= @user.role %>
		</p>
	</div>

	<%= link_to t('all.edit'), edit_user_path(@user), :class => 'btn btn-default btn-xs' %>
	<%= link_to t('all.back'), users_path, :class => 'btn btn-default btn-xs' %>
</div>

app/views/vms/edit.html.erb
Edit

app/views/vms/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  <h4><%= t('vms.listing') %></h4>
  </div>

  	<div class="panel-body" style="max-height:800px; overflow-y: auto; bgcolor:#000000;">
	  <table class="table table-hover">
	    <thead>
	      <tr>
	        <th><%= t('vms.name') %></th>
	        <th><%= t('vms.hash') %></th>
	        <th><%= t('vms.subname') %></th>
	        <th colspan="3"></th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @vms.each do |vm| %>
	        <tr>
	          <td><%= vm.name %></td>
	          <td><%= vm.vhash %></td>
	          <td><%= vm.subname %></td>
	          <td><% link_to t('vms.show'), vm, :class => 'btn btn-default btn-xs' %></td>
	          <td><% link_to t('vms.edit'), edit_vm_path(vm), :class => 'btn btn-default btn-xs' %></td>
	          <td><% link_to t('vms.delete'), vm, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>

  <br>

  <%= link_to t('vms.new'), new_vm_path, :class => 'btn btn-default btn-xs' %>
</div>

app/views/vms/show.html.erb
Show